import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { SessionProvider } from "next-auth/react";
=======
>>>>>>> parent of 65da530 (taskpal)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TaskPal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <SessionProvider>
          {children}
        </SessionProvider>
        
=======
        {children}
>>>>>>> parent of 65da530 (taskpal)
      </body>
    </html>
  );
}
